## 55

In [6]:
vec=1:20
mat=matrix(vec, ncol =4)
vec

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20

In [8]:
cumsum(vec)

[1]   1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153 171 190
[20] 210

In [9]:
mat

[,1] [,2] [,3] [,4]
[1,] 1     6   11   16  
[2,] 2     7   12   17  
[3,] 3     8   13   18  
[4,] 4     9   14   19  
[5,] 5    10   15   20

In [10]:
apply ( mat , 2 , cumsum)
apply ( mat , 1 , cumsum)

[,1] [,2] [,3] [,4]
[1,]  1    6   11   16  
[2,]  3   13   23   33  
[3,]  6   21   36   51  
[4,] 10   30   50   70  
[5,] 15   40   65   90

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  7    9   11   13   15  
[3,] 18   21   24   27   30  
[4,] 34   38   42   46   50

## 56

In [14]:
x <- 1 : 10 ; y <- rev ( x )
x

[1]  1  2  3  4  5  6  7  8  9 10

In [15]:
y

[1] 10  9  8  7  6  5  4  3  2  1

In [16]:
pmax( x , y ) ; pmin ( x , y )

[1] 10  9  8  7  6  6  7  8  9 10

[1] 1 2 3 4 5 5 4 3 2 1

## 57

In [ ]:
n <- 17

In [18]:
integrate(dnorm, -1.96, 1,96)

0 with absolute error < 0